In [60]:
#Importing required libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Generate a dummy dataset.
X = np.random.randint(10,50,60).reshape(20,3) 
X.shape

# mean Centering the data  
X_meaned = X - np.mean(X , axis = 0)
#X_meaned
#X_meaned.shape


(20, 3)

In [42]:
# calculating the covariance matrix of the mean-centered data.
cov_mat = np.cov(X_meaned , rowvar = False)
cov_mat.shape

(3, 3)

In [50]:
#Calculating Eigenvalues and Eigenvectors of the covariance matrix
evalues, evectors = np.linalg.eigh(cov_mat)
evalues
evectors

array([[ 0.96506413,  0.07388987, -0.25137923],
       [ 0.19060396, -0.85628461,  0.48004874],
       [-0.17978143, -0.51119169, -0.84045326]])

In [52]:
#sort the eigenvalues in descending order
sortedindex = np.argsort(evalues)[::-1]
 
sortedevalue = evalues[sortedindex]
#similarly sort the eigenvectors 
sortedevectors = evectors[:,sortedindex]

sortedevectors

array([[-0.25137923,  0.07388987,  0.96506413],
       [ 0.48004874, -0.85628461,  0.19060396],
       [-0.84045326, -0.51119169, -0.17978143]])

In [56]:
# select the first n eigenvectors, n is desired dimension
# of our final reduced data.
 
n_components = 2 #you can select any number of components.
evectorsubset = sortedevectors[:,0:n_components]

evectorsubset

array([[-0.25137923,  0.07388987],
       [ 0.48004874, -0.85628461],
       [-0.84045326, -0.51119169]])

In [57]:
#Transform the data 
X_reduced = np.dot(evectorsubset.transpose(),X_meaned.transpose()).transpose()

X_reduced

array([[ 11.76813534,  10.87294164],
       [  1.26929738,   5.79059805],
       [ -9.16907921,  16.46749769],
       [ -7.7530069 , -16.86373914],
       [ 26.45272581,  -3.86974886],
       [ 24.49016286,  -7.79922106],
       [  2.85169719,  17.61269061],
       [-14.08447942,  -8.56605864],
       [  4.65235563,  -5.60380598],
       [-17.51904535,   1.0687043 ],
       [  3.20011125,  -1.2996675 ],
       [-17.69777941,  11.47818352],
       [ -6.61586265,   7.00569147],
       [  2.61408869,  -7.82234999],
       [ 10.05390016,  12.80718049],
       [ -5.91156005, -18.74926509],
       [-12.53530791,  -9.69354629],
       [  5.53054584,  22.17595729],
       [ -5.80557887, -17.47921459],
       [  4.20867965,  -7.53282792]])